server:
   port: 9095
   
   
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
             
      
      
      
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: EMPLOYEE-SERVICE
        uri: lb://EMPLOYEE-SERVICE
        predicates:
          - Path=/employees/**
        filters:
        - name: CircuitBreaker
          args:
               name: EMPLOYEE-SERVICE
               fallbackuri: forward:/employeesFallback
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
          - Path=/department/**
        filters:
        - name: CircuitBreaker
          args:
               name: DEPARTMENT-SERVICE
               fallbackuri: forward:/departmentFallback
               