server:
  port: 8092
  
  
spring:
  application:
    name: Department-Service
      
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   

zipkin:
 base-url: http://localhost:9411/  