server:
  port: 8091

spring:
  application:
    name: Employee-Service
      
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  

      
zipkin:
 base-url: http://localhost:9411/      
      